### ISSUE TITLE
access raven from dock mode

### ISSUE THREAD

**Issue by dmerit** [solus-project/docs#11]
When using dock mode instead of panel mode, I can open Raven, but it will not stay open to access it. 
the instant my mouse leave the dock to access raven, Raven just retracts, taunting my efforts.
Dock mode was a wonderful discovery to me, but to resize the length to 100% also makes for an insane amount vertical space for the icons.
Solus Budgie has pulled me away from 10 years of loving Xfce, no regrets, you are all creating a fantastic distro, or operating system if you are from system76.  
Cheers

**Comment by JoshStrobl** [comment]
Budgie issues should be filed to https://github.com/budgie-desktop/budgie-desktop.
